FROM hmctspublic.azurecr.io/base/java:openjdk-11-debug-distroless-1.2

WORKDIR /opt/app
USER hmcts

COPY --chown=hmcts:hmcts gradlew build.gradle runTests.sh /opt/app/
COPY --chown=hmcts:hmcts .gradle /opt/app/.gradle/
COPY --chown=hmcts:hmcts gradle /opt/app/gradle/
COPY --chown=hmcts:hmcts src /opt/app/src/

ENTRYPOINT ["./runTests.sh"]
