FROM hmctspublic.azurecr.io/base/java:openjdk-11-debug-distroless-1.4

WORKDIR /opt/app
USER hmcts

COPY --chown=hmcts:hmcts . /opt/app/

RUN ["/busybox/sh", "-c", "gradlew --info --no-daemon --init-gradle init.gradle testClasses smokeTestClasses functionalTestClasses || exit 0"]

ENTRYPOINT ["sh", "runTests.sh"]
