FROM hmctspublic.azurecr.io/base/java:openjdk-11-debug-distroless-1.4

WORKDIR /opt/app
USER hmcts

COPY --chown=hmcts:hmcts . /opt/app/

RUN ["/busybox/sh", "-c", "gradlew --info --no-daemon testClasses || exit 0"]
RUN ["/busybox/sh", "-c", "gradlew --info --no-daemon smokeTestClasses || exit 0"]
RUN ["/busybox/sh", "-c", "gradlew --info --no-daemon functionalTestClasses || exit 0"]

ENTRYPOINT ["sh", "runTests.sh"]
